name: K8s_Apps
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'manifests/***'

env:
  IMAGE_TAG: $(echo ${{ github.sha }} | cut -c1-4)
  NODE_VERSION: 20.11.1

jobs:
    deploy:
        name: DeployApps
        permissions:
          contents: read
          issues: read
          checks: write
          pull-requests: write
          id-token: write
        runs-on: ubuntu-latest
        environment: Dev
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
        
            #   https://github.com/google-github-actions/auth
            - name: Authenticate with Google Cloud
              uses: 'google-github-actions/auth@v2'
              with:
                workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITYPROVIDER }}
                service_account: ${{ secrets.SERVICE_ACCOUNT }}
        
            - name: Configure kubectl
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: ${{ secrets.PROJECT_ID }}
    
            - name: Cluster Connection
              run: |
                gcloud components install gke-gcloud-auth-plugin
                export USE_GKE_GCLOUD_AUTH_PLUGIN=True
                gcloud container clusters get-credentials cohere-main-gke --region=us-central1
                kubectl config get-contexts
                kubectl config current-context

            - name: Deploy App w Database
              run: |
                kubectl apply -f manifests/cohere-app.yaml
                kubectl apply -f manifests/postgress.yaml